### ISSUE TITLE
Dash does not sync anymore, hangs at 99%

### ISSUE THREAD

**Issue by valsha** [btcpayserver/dockerfile-deps#54]
https://github.com/btcpayserver/btcpayserver/issues/4206
please update dash to 18.0.2
thank you.

**Comment by NicolasDorier** [comment]
probably need to be v18.1.0 please ask to the dash community, we don't maintain it ourselves.

**Comment by valsha** [comment]
yes, correct v18.1.0

**Comment by valsha** [comment]
maybe @strophy can help?

**Comment by valsha** [comment]
@NicolasDorier can you please check PR https://github.com/btcpayserver/dockerfile-deps/pull/58
Thank you.

**Comment by NicolasDorier** [comment]
Closing this, bump fixed it https://github.com/btcpayserver/btcpayserver/issues/4206
